language: c
sudo: required
before_install:
  - sudo apt-get -qq update
  - curl -O http://libsdl.org/release/SDL2-2.0.4.tar.gz
  - tar -xzvf SDL2-2.0.4.tar.gz
install: cd SDL2-2.0.4 && ./configure && make && sudo make install
before_script: cd ..
script: make
env:
  global:
  - LD_LIBRARY_PATH: "/usr/local/lib"
